"""The public API of `jhmesh` (review-4 A4-9): every module's `__all__`, pinned.

A name added to, or dropped from, a module's `__all__` changes what users of the published package may rely on, so
it has to change here too, on purpose. Underscore names are private and never listed.
"""

import ast
import importlib
import os
import pkgutil
import subprocess
import sys
from pathlib import Path

import pytest

import jhmesh
from jhmesh import client, sar, state

API: dict[str, list[str]] = {
    "jhmesh": [],
    "jhmesh.access": ["AccessMessage"],
    "jhmesh.advert": [
        "JUNG_COMPANY_ID",
        "JungAdvertisement",
        "mac_from_uuid",
        "parse_jung_advertisement",
        "parse_manufacturer_data",
    ],
    "jhmesh.audit": [
        "CLIENT_MODELS",
        "Finding",
        "ModelAudit",
        "NodeAudit",
        "PAUSE",
        "Query",
        "SCENE_MODELS",
        "SETTINGS",
        "audit_node",
        "client_exchange",
        "evaluate",
        "export_keys",
        "export_settings",
        "key_queries",
        "report",
        "run_chunked",
        "setting_queries",
    ],
    "jhmesh.cdb": [
        "CDB",
        "Element",
        "InvalidExport",
        "MAX_DEPTH",
        "Node",
        "Provisioner",
        "UUID_PATTERN",
        "canonical_uuid",
        "is_virtual",
        "model_publication",
        "model_subscriptions",
        "parse_address",
        "virtual_address",
    ],
    "jhmesh.client": [
        "AccessMessage",
        "CLASSIFY_CACHE_SIZE",
        "FILTER_ACK_TIMEOUT",
        "FILTER_RESEND_TRIES",
        "FILTER_RESEND_WAIT",
        "FILTER_SET_TRIES",
        "FOREIGN_SOURCE_REPORT_INTERVAL",
        "GATT_TIMEOUT",
        "Heartbeat",
        "IVUpdateRefused",
        "IV_ABANDONED_ABORTED",
        "IV_ABANDONED_NOT_TAKEN",
        "IV_BEACON_INTERVAL",
        "IV_BEACON_INTERVAL_MAX",
        "IV_INDEX_MAX",
        "IV_ORIGIN_BEACON",
        "IV_ORIGIN_LOCAL",
        "IV_RECOVERY_MIN_INTERVAL",
        "IV_UPDATE_MAX_STATE",
        "IV_UPDATE_MIN_STATE",
        "LocalState",
        "MESH_PROXY_DATA_IN",
        "MESH_PROXY_DATA_OUT",
        "MESH_PROXY_SERVICE",
        "NET_KEY_INDEX",
        "ProxyCandidate",
        "ProxyClient",
        "SAR_ACK_DELAY_INCREMENT",
        "SAR_ACK_RETRANSMISSIONS",
        "SAR_DISCARD_TIMEOUT",
        "SAR_SEGMENTS_THRESHOLD",
        "SAR_SEGMENT_INTERVAL",
        "SEGMENT_ACK_TIMEOUT",
        "SEGMENT_RESTARTS",
        "SEGMENT_RETRIES",
        "SEQ_GUARD_FIRST_BEACON",
        "SEQ_MAX",
        "SEQ_TX_LIMIT",
        "SequenceExhausted",
        "SequenceStalled",
        "StateInUse",
        "check_range",
        "classify_proxy_advert",
    ],
    "jhmesh.commission": [
        "CALLER_PHASES",
        "CompositionMismatch",
        "NOT_COVERED",
        "PHASES",
        "Plan",
        "SUPPORTED_SERVERS",
        "Shape",
        "Step",
        "device_class",
        "plan",
    ],
    "jhmesh.config_messages": [
        "AppKeyList",
        "AppKeyStatus",
        "BeaconStatus",
        "CONFIG_APPKEY_ADD",
        "CONFIG_APPKEY_DELETE",
        "CONFIG_APPKEY_GET",
        "CONFIG_APPKEY_LIST",
        "CONFIG_APPKEY_STATUS",
        "CONFIG_APPKEY_UPDATE",
        "CONFIG_BEACON_GET",
        "CONFIG_BEACON_SET",
        "CONFIG_BEACON_STATUS",
        "CONFIG_COMPOSITION_DATA_GET",
        "CONFIG_COMPOSITION_DATA_STATUS",
        "CONFIG_DEFAULT_TTL_GET",
        "CONFIG_DEFAULT_TTL_SET",
        "CONFIG_DEFAULT_TTL_STATUS",
        "CONFIG_FRIEND_GET",
        "CONFIG_FRIEND_STATUS",
        "CONFIG_GATT_PROXY_GET",
        "CONFIG_GATT_PROXY_SET",
        "CONFIG_GATT_PROXY_STATUS",
        "CONFIG_HEARTBEAT_PUBLICATION_GET",
        "CONFIG_HEARTBEAT_PUBLICATION_SET",
        "CONFIG_HEARTBEAT_PUBLICATION_STATUS",
        "CONFIG_HEARTBEAT_SUBSCRIPTION_GET",
        "CONFIG_HEARTBEAT_SUBSCRIPTION_SET",
        "CONFIG_HEARTBEAT_SUBSCRIPTION_STATUS",
        "CONFIG_KEY_REFRESH_PHASE_GET",
        "CONFIG_KEY_REFRESH_PHASE_SET",
        "CONFIG_KEY_REFRESH_PHASE_STATUS",
        "CONFIG_MODEL_APP_BIND",
        "CONFIG_MODEL_APP_STATUS",
        "CONFIG_MODEL_APP_UNBIND",
        "CONFIG_MODEL_PUBLICATION_GET",
        "CONFIG_MODEL_PUBLICATION_SET",
        "CONFIG_MODEL_PUBLICATION_STATUS",
        "CONFIG_MODEL_SUBSCRIPTION_ADD",
        "CONFIG_MODEL_SUBSCRIPTION_DELETE",
        "CONFIG_MODEL_SUBSCRIPTION_DELETE_ALL",
        "CONFIG_MODEL_SUBSCRIPTION_OVERWRITE",
        "CONFIG_MODEL_SUBSCRIPTION_STATUS",
        "CONFIG_NAMES",
        "CONFIG_NETKEY_ADD",
        "CONFIG_NETKEY_DELETE",
        "CONFIG_NETKEY_GET",
        "CONFIG_NETKEY_LIST",
        "CONFIG_NETKEY_STATUS",
        "CONFIG_NETKEY_UPDATE",
        "CONFIG_NETWORK_TRANSMIT_GET",
        "CONFIG_NETWORK_TRANSMIT_SET",
        "CONFIG_NETWORK_TRANSMIT_STATUS",
        "CONFIG_NODE_IDENTITY_GET",
        "CONFIG_NODE_IDENTITY_SET",
        "CONFIG_NODE_IDENTITY_STATUS",
        "CONFIG_NODE_RESET",
        "CONFIG_NODE_RESET_STATUS",
        "CONFIG_RELAY_GET",
        "CONFIG_RELAY_SET",
        "CONFIG_RELAY_STATUS",
        "CONFIG_SIG_MODEL_APP_GET",
        "CONFIG_SIG_MODEL_APP_LIST",
        "CONFIG_SIG_MODEL_SUBSCRIPTION_GET",
        "CONFIG_SIG_MODEL_SUBSCRIPTION_LIST",
        "CONFIG_VENDOR_MODEL_APP_GET",
        "CONFIG_VENDOR_MODEL_APP_LIST",
        "CONFIG_VENDOR_MODEL_SUBSCRIPTION_GET",
        "CONFIG_VENDOR_MODEL_SUBSCRIPTION_LIST",
        "CompositionData",
        "CompositionElement",
        "ConfigStatus",
        "DefaultTtlStatus",
        "FEATURE_NOT_SUPPORTED",
        "FriendStatus",
        "GattProxyStatus",
        "HEARTBEAT_INDEFINITE",
        "HEARTBEAT_PERIOD_OFF",
        "HEARTBEAT_TTL_MAX",
        "HeartbeatPublicationStatus",
        "HeartbeatSubscriptionStatus",
        "KEY_CARRYING_OPCODES",
        "KeyRefreshPhaseStatus",
        "ModelAppList",
        "ModelAppStatus",
        "ModelPublicationStatus",
        "ModelSubscriptionList",
        "ModelSubscriptionStatus",
        "NODE_IDENTITY_NOT_SUPPORTED",
        "NODE_IDENTITY_RUNNING",
        "NODE_IDENTITY_STOPPED",
        "NetKeyList",
        "NetKeyStatus",
        "NetworkTransmitStatus",
        "NodeIdentityStatus",
        "NodeResetStatus",
        "PUBLISH_TTL_DEFAULT",
        "RelayStatus",
        "STATUS_SUCCESS",
        "appkey_add",
        "appkey_delete",
        "appkey_get",
        "appkey_update",
        "beacon_get",
        "beacon_set",
        "byte_count",
        "composition_data_get",
        "decode_appkey_list",
        "decode_appkey_status",
        "decode_beacon_status",
        "decode_composition_data",
        "decode_config",
        "decode_default_ttl_status",
        "decode_friend_status",
        "decode_gatt_proxy_status",
        "decode_heartbeat_publication_status",
        "decode_heartbeat_subscription_status",
        "decode_key_refresh_phase_status",
        "decode_model_app_list",
        "decode_model_app_status",
        "decode_model_id",
        "decode_model_publication_status",
        "decode_model_subscription_list",
        "decode_model_subscription_status",
        "decode_netkey_list",
        "decode_netkey_status",
        "decode_network_transmit_status",
        "decode_node_identity_status",
        "decode_node_reset_status",
        "decode_relay_status",
        "default_ttl_get",
        "default_ttl_set",
        "describe_config",
        "echoes",
        "encode_model_id",
        "friend_get",
        "gatt_proxy_get",
        "gatt_proxy_set",
        "heartbeat_count_range",
        "heartbeat_period_log",
        "heartbeat_period_seconds",
        "heartbeat_publication_get",
        "heartbeat_publication_set",
        "heartbeat_subscription_get",
        "heartbeat_subscription_off",
        "heartbeat_subscription_set",
        "is_vendor_model",
        "key_refresh_phase_get",
        "key_refresh_phase_set",
        "model_app_bind",
        "model_app_get",
        "model_app_unbind",
        "model_get",
        "model_id",
        "model_id_str",
        "model_publication_get",
        "model_publication_set",
        "model_subscription_add",
        "model_subscription_delete",
        "model_subscription_delete_all",
        "model_subscription_get",
        "model_subscription_overwrite",
        "netkey_add",
        "netkey_delete",
        "netkey_get",
        "netkey_update",
        "network_transmit_get",
        "network_transmit_set",
        "node_identity_get",
        "node_identity_set",
        "node_reset",
        "relay_get",
        "relay_set",
    ],
    "jhmesh.crypto": [
        "AppKeyMaterial",
        "NetKeyMaterial",
        "ZERO16",
        "ZERO32",
        "aes_cmac",
        "aes_ecb",
        "ccm_decrypt",
        "ccm_encrypt",
        "hmac_sha256",
        "k1",
        "k2",
        "k3",
        "k4",
        "k5",
        "s1",
        "s2",
    ],
    "jhmesh.devices": [
        "ALL_BLINDS",
        "ALL_LIGHTS",
        "ALL_SCENES",
        "ALL_SLATS",
        "ALL_SOCKETS",
        "ALL_THERMOSTATS",
        "BATTERY_PIDS",
        "BLIND_FUNCTION",
        "BLIND_ONLY_PIDS",
        "BUTTON_LETTERS",
        "Blind",
        "BuildContext",
        "Button",
        "DETECTOR_PIDS",
        "DEVICE_TYPE_GROUPS",
        "Detector",
        "Device",
        "Devices",
        "ELEMENT_GROUP_PREFIX",
        "ELEMENT_RULES",
        "ElementRule",
        "GATEWAY_PID",
        "GROUP_RANGE",
        "INPUT_NAMES",
        "INSERT_FUNCTIONS",
        "InvalidMetadata",
        "KEY_LAYOUT_PIDS",
        "KEY_LOCATION",
        "KEY_POSITIONS",
        "KeyConnection",
        "LAMP_FUNCTIONS",
        "LAMP_LEVEL_MODELS",
        "LOAD_LOCATIONS",
        "Light",
        "MINI_ACTUATOR_PIDS",
        "Metadata",
        "MeteredLoad",
        "PP2_PIDS",
        "PRESENCE_DETECTOR_PID",
        "PUSH_BUTTON_PIDS",
        "SCENE_CLIENT",
        "SOCKET_PIDS",
        "SceneDef",
        "Socket",
        "THERMOSTAT_PIDS",
        "TIMER_SCENE_PREFIX",
        "TIME_KEEPER_ADDRESS",
        "TIME_KEEPER_GROUP",
        "TIME_SERVER",
        "TIME_SETUP_SERVER",
        "Thermostat",
        "as_int",
        "build_devices",
        "ctl_temperature_element",
        "element_group_address",
        "expected_device_count",
        "insert_function",
        "insert_mismatch",
        "is_room",
        "key_position",
        "load_kind",
        "meta_list",
        "meter_element",
        "pick_insert",
        "room_names",
        "slat_element",
        "time_keeper_candidates",
        "with_key_lock",
    ],
    "jhmesh.export": [
        "ALLOCATION_MARGIN",
        "Allocation",
        "AllocationCrowded",
        "DEFAULT_GROUP_ICON",
        "DEFAULT_SCENE_ICON",
        "DeviceRow",
        "ExportError",
        "FUNCTION_KEY_MODE",
        "GROUP_FUNCTIONS",
        "InvalidName",
        "KEY_MODE_GATEWAY",
        "KEY_MODE_LIGHT",
        "KEY_MODE_MOVE",
        "KEY_MODE_PROPERTY",
        "KEY_MODE_RTR",
        "KEY_MODE_SCENE",
        "KEY_MODE_SERVERS",
        "KEY_MODE_SWITCH",
        "Layout",
        "META_KEYS",
        "ModelChange",
        "NewerExportError",
        "ProjectFile",
        "RENAME_MAX_LENGTH",
        "RoomLink",
        "SHARE_KEYS",
        "Style",
        "cdb_element_groups",
        "check_name",
        "function_code",
        "group_addresses_in_use",
        "guess_actuator_function",
        "guess_insert_type",
        "has_model",
        "hexaddr",
        "mac_from_uuid",
        "name_length",
        "now_timestamp",
        "pick_free",
        "raw_model",
        "scene_infos",
        "suffixed_name",
        "timestamp_advanced",
        "write_private",
        "write_private_with_backup",
    ],
    "jhmesh.fileio": [
        "BACKUP_GENERATIONS",
        "PRIVATE_MODE",
        "atomic_write",
        "backup_paths",
        "copy_private",
        "fsync_dir",
        "keep_backup",
        "temp_path",
    ],
    "jhmesh.keyrefresh": [
        "KeyRefreshFollower",
        "KeyRefreshRecord",
        "MAX_CANDIDATES",
        "Moved",
        "PROOF_BEACON",
        "PROOF_EXPORT",
        "PROOF_PROXY",
        "PROOF_STATUSES",
        "describe_proof",
    ],
    "jhmesh.merge": [
        "Change",
        "IDENTITY",
        "Key",
        "MISSING",
        "Row",
        "apply_changes",
        "diff_documents",
    ],
    "jhmesh.messages": [
        "ALTITUDE_TOO_HIGH",
        "BATTERY_CHARGING",
        "BATTERY_INDICATOR",
        "BATTERY_PRESENCE",
        "BATTERY_SERVICEABILITY",
        "GEN_ADMIN_PROPS_STATUS",
        "GEN_ADMIN_PROP_STATUS",
        "GEN_BATTERY_STATUS",
        "GEN_DELTA_SET",
        "GEN_DELTA_SET_UNACK",
        "GEN_DTT_STATUS",
        "GEN_LEVEL_GET",
        "GEN_LEVEL_SET",
        "GEN_LEVEL_SET_UNACK",
        "GEN_LEVEL_STATUS",
        "GEN_LOCATION_GLOBAL_STATUS",
        "GEN_MANU_PROP_STATUS",
        "GEN_MOVE_SET",
        "GEN_MOVE_SET_UNACK",
        "GEN_ONOFF_GET",
        "GEN_ONOFF_SET",
        "GEN_ONOFF_SET_UNACK",
        "GEN_ONOFF_STATUS",
        "GEN_ONPOWERUP_GET",
        "GEN_ONPOWERUP_SET",
        "GEN_ONPOWERUP_STATUS",
        "GEN_USER_PROP_STATUS",
        "HEALTH_ATTENTION_STATUS",
        "HEALTH_CURRENT_STATUS",
        "HEALTH_FAULT_STATUS",
        "HealthFaults",
        "JUNG_CID",
        "LIGHT_CTL_DEFAULT_GET",
        "LIGHT_CTL_DEFAULT_SET",
        "LIGHT_CTL_DEFAULT_STATUS",
        "LIGHT_CTL_GET",
        "LIGHT_CTL_SET",
        "LIGHT_CTL_SET_UNACK",
        "LIGHT_CTL_STATUS",
        "LIGHT_CTL_TEMP_GET",
        "LIGHT_CTL_TEMP_RANGE_GET",
        "LIGHT_CTL_TEMP_RANGE_SET",
        "LIGHT_CTL_TEMP_RANGE_STATUS",
        "LIGHT_CTL_TEMP_SET",
        "LIGHT_CTL_TEMP_SET_UNACK",
        "LIGHT_CTL_TEMP_STATUS",
        "LIGHT_LIGHTNESS_DEFAULT_GET",
        "LIGHT_LIGHTNESS_DEFAULT_SET",
        "LIGHT_LIGHTNESS_DEFAULT_STATUS",
        "LIGHT_LIGHTNESS_GET",
        "LIGHT_LIGHTNESS_RANGE_GET",
        "LIGHT_LIGHTNESS_RANGE_SET",
        "LIGHT_LIGHTNESS_RANGE_STATUS",
        "LIGHT_LIGHTNESS_SET",
        "LIGHT_LIGHTNESS_SET_UNACK",
        "LIGHT_LIGHTNESS_STATUS",
        "SCENE_DELETE",
        "SCENE_DELETE_UNACK",
        "SCENE_GET",
        "SCENE_NOT_FOUND",
        "SCENE_RECALL",
        "SCENE_RECALL_UNACK",
        "SCENE_REGISTER_FULL",
        "SCENE_REGISTER_GET",
        "SCENE_REGISTER_STATUS",
        "SCENE_STATUS",
        "SCENE_STORE",
        "SCENE_STORE_UNACK",
        "SENSOR_DESCRIPTOR_STATUS",
        "SENSOR_GET",
        "SENSOR_STATUS",
        "SIG_PROPERTY_LIST_OPCODES",
        "SIG_PROP_GET",
        "STATE_STEP",
        "SceneRegister",
        "SceneStatus",
        "SensorDescriptor",
        "TAI_EPOCH",
        "TAI_UTC_DELTA",
        "TIME_ROLE_CLIENT",
        "TIME_ROLE_RELAY",
        "TIME_ROLE_STATUS",
        "TIME_SET",
        "TIME_STATUS",
        "TIME_ZONE_STATUS",
        "TRANSITION_MAX_SECONDS",
        "TRANSITION_MAX_STEPS",
        "TRANSITION_STEP_MS",
        "TRANSITION_UNKNOWN",
        "TimeStatus",
        "TimeZoneStatus",
        "VENDOR_PROPERTY_LIST_OPCODES",
        "VENDOR_PROPERTY_SET_OPCODES",
        "VENDOR_PROPERTY_STATUS_OPCODES",
        "battery_status",
        "decode_health_fault_status",
        "decode_scene_register_status",
        "decode_scene_status",
        "decode_time_role_status",
        "decode_time_status",
        "decode_time_zone_status",
        "decode_transition",
        "describe",
        "encode_transition",
        "generic_battery_get",
        "generic_delta_set",
        "generic_level_get",
        "generic_level_set",
        "generic_location_global_get",
        "generic_location_global_set",
        "generic_move_set",
        "generic_onoff_get",
        "generic_onoff_set",
        "generic_onpowerup_get",
        "generic_onpowerup_set",
        "generic_properties_get",
        "generic_property_get",
        "generic_property_set",
        "health_attention_set",
        "health_fault_clear",
        "health_fault_get",
        "health_fault_name",
        "health_fault_test",
        "light_ctl_default_get",
        "light_ctl_default_set",
        "light_ctl_get",
        "light_ctl_set",
        "light_ctl_temperature_get",
        "light_ctl_temperature_range_get",
        "light_ctl_temperature_range_set",
        "light_ctl_temperature_set",
        "light_lightness_default_get",
        "light_lightness_default_set",
        "light_lightness_get",
        "light_lightness_range_get",
        "light_lightness_range_set",
        "light_lightness_set",
        "location_global",
        "location_global_fields",
        "next_tid",
        "property_ids",
        "remaining_time",
        "scene_delete",
        "scene_get",
        "scene_recall",
        "scene_register_get",
        "scene_store",
        "sensor_descriptor_get",
        "sensor_descriptors",
        "sensor_get",
        "sensor_values",
        "set_shown_by",
        "time_get",
        "time_role_get",
        "time_role_set",
        "time_set",
        "time_zone_get",
        "vendor_properties_get",
        "vendor_property_get",
        "vendor_property_set",
        "vendor_property_status",
    ],
    "jhmesh.onboarding": [
        "CommissioningError",
        "DeviceCount",
        "commission",
        "free_unicast_block",
        "missing_devices",
        "node_entry",
        "node_for",
        "record",
    ],
    "jhmesh.pdu": [
        "ALL_FRIENDS",
        "ALL_NODES",
        "ALL_PROXIES",
        "ALL_RELAYS",
        "BEACON_PRIVATE",
        "BEACON_UNPROVISIONED",
        "FILTER_BLACKLIST",
        "FILTER_WHITELIST",
        "NONCE_APP",
        "NONCE_DEVICE",
        "NetworkPDU",
        "PROXY_BEACON",
        "PROXY_CONFIG",
        "PROXY_NETWORK_PDU",
        "PROXY_PDU_MAX",
        "PROXY_PROVISIONING",
        "ProxyReassembler",
        "SEGMENTS_MAX",
        "SecureNetworkBeacon",
        "SegmentInfo",
        "UNASSIGNED",
        "UNSEGMENTED_UPPER_MAX",
        "decode_opcode",
        "encode_opcode",
        "is_group",
        "is_unicast",
        "lower_segments_access",
        "lower_unsegmented_access",
        "network_decrypt",
        "network_encrypt",
        "parse_beacon",
        "parse_lower",
        "parse_private_beacon",
        "proxy_config_add_addresses",
        "proxy_config_set_filter",
        "proxy_frame",
        "secure_network_beacon",
        "segment_ack",
        "seq_auth_from",
        "upper_decrypt",
        "upper_encrypt",
        "upper_encrypt_app",
        "upper_encrypt_dev",
    ],
    "jhmesh.plan": [
        "APP_KEY_INDEX",
        "Check",
        "ConfigStep",
        "DESTRUCTIVE_KINDS",
        "Difference",
        "SCENE_SERVER",
        "STEP_KINDS",
        "bind_step",
        "config_step",
        "config_steps",
        "deletable",
        "destructive",
        "element_of",
        "ordered",
        "preflight_checks",
        "register_check",
        "replay",
        "step_kind",
    ],
    "jhmesh.properties": [
        "ACTUATOR_FUNCTION",
        "ALL_PRODUCTS",
        "ASCII_VERSION",
        "AstroRegister",
        "AstroRegisterCodec",
        "AstroStatus",
        "BLIND_MODE",
        "BOOL",
        "BUTTON_LAYOUT",
        "Bool",
        "Codec",
        "Counter",
        "DELAY_MS",
        "DETECTORS",
        "DateUTC",
        "Duration",
        "EDGE_BEHAVIOUR",
        "ENFORCED_OUTPUT",
        "ENFORCE_LOCK",
        "ENFORCE_UNLOCK",
        "ENFORCE_VALUE",
        "EdgeDetection",
        "EdgeDetectionCodec",
        "EnforcedOutput",
        "EnforcedOutputCodec",
        "Enum",
        "FORCED_OFF",
        "Flags",
        "GATEWAY",
        "GATEWAY_STATUS_FLAGS",
        "InsertId",
        "Int",
        "KEY_MODE",
        "KEY_PROPERTY_MODE",
        "KEY_VALUE_UP",
        "KeyEvent",
        "LED_COLOURS",
        "LED_HOSTS",
        "LED_PALETTES",
        "LOCKABLE",
        "LedMode",
        "MINI_ACTUATORS",
        "MS32",
        "NOT_GATEWAY",
        "PB_MAINS",
        "PERCENT",
        "POSITION",
        "PRESENCE_DETECTOR",
        "PRIORITY_LOCKOUT",
        "PRIORITY_NORMAL",
        "PROPERTIES",
        "PUSH_BUTTONS",
        "Percent",
        "PropertyMode",
        "PropertySpec",
        "RAW",
        "REDACTED",
        "RGB_MODE",
        "RTR",
        "RgbMode",
        "S16",
        "SIG_HARDWARE_REVISION",
        "SIG_MANUFACTURER_NAME",
        "SIG_PROPERTIES",
        "SIG_SOFTWARE_VERSION",
        "SOCKETS",
        "Scaled",
        "SceneConfig",
        "TEMP_001C",
        "TWO_GANG",
        "Text",
        "Threshold",
        "ThresholdCodec",
        "Timestamp7",
        "U16",
        "U24",
        "U32",
        "U8",
        "UNLOCK",
        "VERSION_LE",
        "WIND_ALARM",
        "by_name",
        "decode",
        "describe_status",
        "encode",
        "for_product",
        "format_value",
        "key_lock",
        "key_lock_values",
        "led_colour_name",
        "led_palette",
        "led_property_id",
        "lock_output",
        "parse_version",
        "spec_for",
        "supported",
    ],
    "jhmesh.provisioning": [
        "ALGORITHM_HMAC_SHA256",
        "AUTH_STATIC_OOB",
        "CAPABILITIES",
        "COMPLETE",
        "CONFIRMATION",
        "Capabilities",
        "DATA",
        "DEFAULT_ATTENTION",
        "FAILED",
        "GATT_WRITE_TIMEOUT",
        "INVITE",
        "MESH_PROVISIONING_DATA_IN",
        "MESH_PROVISIONING_DATA_OUT",
        "MESH_PROVISIONING_SERVICE",
        "Method",
        "PROTOCOL_TIMEOUT",
        "PUBLIC_KEY",
        "Provisioner",
        "ProvisioningData",
        "ProvisioningError",
        "ProvisioningFailed",
        "ProvisioningResult",
        "ProvisioningTimeout",
        "RANDOM",
        "START",
        "State",
        "UnprovisionedDevice",
        "capability_record",
        "choose_method",
        "confirmation",
        "confirmation_key",
        "confirmation_salt",
        "decrypt_provisioning_data",
        "device_key",
        "ecdh_secret",
        "encrypt_provisioning_data",
        "generate_private_key",
        "invite",
        "parse_provisioning_service_data",
        "parse_unprovisioned_beacon",
        "pdu",
        "provision",
        "provisioning_salt",
        "public_key_bytes",
        "session_key",
        "session_nonce",
        "start_no_oob",
    ],
    "jhmesh.sar": [
        "SAR_ACK_DELAY_INCREMENT",
        "SAR_ACK_RETRANSMISSIONS",
        "SAR_DISCARD_TIMEOUT",
        "SAR_SEGMENTS_THRESHOLD",
        "SAR_SEGMENT_INTERVAL",
        "SEGMENT_ACK_TIMEOUT",
        "SEGMENT_RESTARTS",
        "SEGMENT_RETRIES",
    ],
    "jhmesh.sniffer": [
        "AD_BEACON",
        "AD_MESSAGE",
        "AD_PB_ADV",
        "COPY_MEMORY",
        "LINKTYPE_NORDIC_BLE",
        "MeshDecoder",
        "PRUNE_EVERY",
        "SEGMENT_MEMORY",
        "SniffRecord",
        "ad_structures",
        "format_address",
        "mesh_records",
        "read_pcap",
    ],
    "jhmesh.standalone": [
        "BEACON_WAIT",
        "SILENCE_TIMEOUT",
        "StandaloneLink",
        "connect",
        "provision_device",
        "scan_for_proxies",
        "scan_unprovisioned",
    ],
    "jhmesh.state": [
        "IVUpdateRefused",
        "IV_ABANDONED_ABORTED",
        "IV_ABANDONED_NOT_TAKEN",
        "IV_INDEX_MAX",
        "IV_ORIGIN_BEACON",
        "IV_ORIGIN_LOCAL",
        "IV_RECOVERY_MIN_INTERVAL",
        "IV_UPDATE_MAX_STATE",
        "IV_UPDATE_MIN_STATE",
        "LocalState",
        "SEQ_GUARD_FIRST_BEACON",
        "SEQ_MAX",
        "SEQ_TX_LIMIT",
        "SequenceExhausted",
        "SequenceStalled",
        "StateInUse",
        "check_range",
    ],
    "jhmesh.stats": ["LinkStats"],
    "jhmesh.vault": [
        "GROUP_CEILING",
        "RangeError",
        "Ranges",
        "RefreshProgress",
        "Vault",
        "VaultError",
        "VaultNode",
        "choose_ranges",
        "recognise",
    ],
    "jhmesh.vaultrefresh": [
        "Target",
        "carry",
        "target_of",
        "wanted",
    ],
    "jhmesh.vendor_models": [
        "ACTION_BLINDS",
        "ACTION_LIGHTNESS",
        "ACTION_LIGHTNESS_CT",
        "ACTION_PAYLOAD_LENGTH",
        "ACTION_SWITCH",
        "ACTION_TEMPERATURE",
        "Action",
        "DAYS",
        "EffectiveTime",
        "JH_SCHEDULER_GET",
        "JH_SCHEDULER_SET",
        "JH_SCHEDULER_STATUS",
        "JUNG_CID",
        "LEVEL_MAX",
        "LEVEL_MIN",
        "LIGHTNESS_MAX",
        "NO_ACTION",
        "SCENE_ACTION_SETUP_GET",
        "SCENE_ACTION_SETUP_SET",
        "SCENE_ACTION_SETUP_STATUS",
        "SCENE_LIST",
        "SCHEDULER_MODEL",
        "SCHEDULE_TYPES",
        "SLOTS",
        "SUB_ACTION",
        "SUB_EFFECTIVE_TIME",
        "SUB_LIST",
        "SUB_NAMES",
        "SUB_SCHEDULE",
        "SceneActionStatus",
        "Schedule",
        "SchedulerStatus",
        "UNSET_TIME",
        "days_mask",
        "decode_action",
        "decode_scene_action_status",
        "decode_scheduler_status",
        "describe_vendor_model",
        "scene_action_get",
        "scene_action_reply_to",
        "scene_action_set",
        "scheduler_action_set",
        "scheduler_get",
        "scheduler_list_get",
        "scheduler_type_set",
    ],
}
# `LocalState` and what goes with it moved from `client` to `state`; `client` still exports them
MOVED_TO_STATE = [
    "IVUpdateRefused",
    "IV_ABANDONED_ABORTED",
    "IV_ABANDONED_NOT_TAKEN",
    "IV_INDEX_MAX",
    "IV_ORIGIN_BEACON",
    "IV_ORIGIN_LOCAL",
    "IV_RECOVERY_MIN_INTERVAL",
    "IV_UPDATE_MAX_STATE",
    "IV_UPDATE_MIN_STATE",
    "LocalState",
    "SEQ_GUARD_FIRST_BEACON",
    "SEQ_MAX",
    "SEQ_TX_LIMIT",
    "SequenceExhausted",
    "SequenceStalled",
    "StateInUse",
    "check_range",
]


@pytest.mark.parametrize("name", sorted(API))
def test_all_is_the_pinned_public_api(name: str) -> None:
    module = importlib.import_module(name)
    assert sorted(module.__all__) == API[name]
    assert len(set(module.__all__)) == len(module.__all__)
    for attr in module.__all__:
        assert not attr.startswith("_"), attr
        assert hasattr(module, attr), attr


def test_every_module_is_pinned() -> None:
    modules = {f"jhmesh.{m.name}" for m in pkgutil.iter_modules(jhmesh.__path__)}
    assert modules | {"jhmesh"} == set(API)


def test_client_re_exports_the_state() -> None:
    assert sorted(state.__all__) == MOVED_TO_STATE
    for attr in MOVED_TO_STATE:
        assert attr in client.__all__
        assert getattr(client, attr) is getattr(state, attr)


def test_importing_the_package_loads_no_dependency() -> None:
    """`import jhmesh` alone stays free of `bleak` and `cryptography` work: every module is imported by name."""
    root = str(Path(jhmesh.__file__).parents[1])
    code = "import sys, jhmesh; print(sorted(m for m in sys.modules if m.split('.')[0] in ('bleak', 'cryptography')))"
    env = {**os.environ, "PYTHONPATH": root}
    out = subprocess.run(  # noqa: S603  # this interpreter, a fixed command
        [sys.executable, "-c", code],
        capture_output=True,
        text=True,
        check=True,
        env=env,
        cwd=root,
    ).stdout
    assert out.strip() == "[]"


def test_every_logger_is_named_under_jhmesh() -> None:
    """A logger named by its module path would be `custom_components.junghome_ble.jhmesh.…` inside Home Assistant,
    out of reach of the documented `jhmesh` logger setting: every one has a literal `jhmesh…` name."""
    names = [
        (path.name, ast.unparse(node.args[0]))
        for path in sorted(Path(jhmesh.__file__).parent.glob("*.py"))
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8")))
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "getLogger"
    ]
    assert len(names) >= 7
    assert [
        (file, name)
        for file, name in names
        if not name.startswith(("'jhmesh", '"jhmesh'))
    ] == []


def test_client_re_exports_the_sar_constants() -> None:
    assert all(getattr(client, attr) is getattr(sar, attr) for attr in sar.__all__)
    assert set(sar.__all__) <= set(client.__all__)
